language: node_js
node_js: stable
branches:
  only:
  - blog_source
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_0cfe0e2935fc_key -iv $encrypted_0cfe0e2935fc_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name “duantao561”
- git config --global user.email "994363029@qq.com"

install:
- npm install hexo-cli -g
- npm install hexo-deployer-git --save
- npm install

before_script:
- npm install -g gulp

script:
- hexo clean
- hexo g

after_success:
- hexo deploy
